name: dockerhub-auto-mirror

on:
  issues:
    types: [opened]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        run: bash <(curl -sL get.docker.com)

      - name: Check issue title and mirror image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          MIRROR_REPO: dockerhub.qingcloud.com/theresa/github-actions
        run: |
          if [[ "${{ github.event.issue.title }}" == mirror* ]]; then
            # Extract the image name and version from the issue title
            IMAGE_NAME=${{ github.event.issue.body }}
            # Define the new image name
            NEW_IMAGE_NAME="${MIRROR_REPO}:${IMAGE_NAME#*:}"

            # Pull the original image
            docker pull ${IMAGE_NAME}

            # Tag the image with the new name
            docker tag ${IMAGE_NAME} ${NEW_IMAGE_NAME}

            # Login to the mirror repository
            echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin ${MIRROR_REPO}

            # Push the new image to the mirror repository
            docker push ${NEW_IMAGE_NAME}
                        IMAGE_URL="dockerhub.qingcloud.com/theresa/github-actions/$NEW_IMAGE_NAME"

            # Close the issue and comment with the new image URL
            curl -X POST \
            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            -H 'Accept: application/vnd.github.v3+json' \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.node_id }}/comments \
            -d '{"body":"镜像已同步到: `$IMAGE_URL`"}'

            # Close the issue
            curl -X PATCH \
            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            -H 'Accept: application/vnd.github.v3+json' \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.node_id }} \
            -d '{"state":"closed"}'
          fi

      - name: Logout from Docker
        if: always()
        run: docker logout
