name: dockerhub-auto-mirror

on:
  issues:
    types: [opened]

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        run: bash <(curl -sL get.docker.com)

      - name: Check issue title and mirror image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          MIRROR_REPO: dockerhub.qingcloud.com/theresa/github-actions
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
        run: |
          if [[ "${{ github.event.issue.title }}" == mirror* ]]; then
            # Extract the image name and version from the issue title
            IMAGE_NAME=${{ github.event.issue.body }}
            # Define the new image name
            NEW_IMAGE_NAME=dockerhub.qingcloud.com/theresa/github-actions:$(echo $IMAGE_NAME | sed 's/[/:.]/-/g')

            # Pull the original image
            docker pull ${IMAGE_NAME}

            # Tag the image with the new name
            docker tag ${IMAGE_NAME} ${NEW_IMAGE_NAME}

            # Login to the mirror repository
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} dockerhub.qingcloud.com

            # Push the new image to the mirror repository
            docker push $NEW_IMAGE_NAME

            gh issue comment "$NUMBER" -b "同步完成: \`$NEW_IMAGE_NAME\`"
            gh issue close "$NUMBER" -r completed
          fi

      - name: Logout from Docker
        if: always()
        run: docker logout
